name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install zip on Windows
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: choco install zip -y

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build and Package
        # すべてのOSで共通してbashを利用する
        shell: bash
        env:
          CGO_ENABLED: 1
          GIN_MODE: release
        run: |
          # OSに応じてバイナリ名を決定
          binary_name="NyanQL"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            binary_name="${binary_name}.exe"
          fi

          # main.goをビルド
          go build -o "${binary_name}" main.go

          # パッケージ用のフォルダ作成
          mkdir release_package

          cp "${binary_name}" release_package/
          cp README.md release_package/
          cp LICENSE.md release_package/
          cp config.json release_package/
          cp api.json release_package/
          cp stamps.db release_package/
          cp -r javascript release_package/
          cp -r logs release_package/
          cp -r sql release_package/
          cp -r ssl release_package/

          # zipを作成 (OS名をファイル名に含める例)
          zip -r "NyanQL_${{ matrix.os }}.zip" release_package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-package
          path: NyanQL_${{ matrix.os }}.zip
